language: generic

services:
  - docker

before_install:
  - echo "--------- Installing dependencies -----------"
  - sudo curl -LO https://nodejs.org/dist/v16.0.0/node-v16.0.0-linux-x64.tar.xz
  - sudo tar -xvf node-v16.0.0-linux-x64.tar.xz
  - sudo cp -r node-v16.0.0-linux-x64/{bin,include,lib,share} /usr/
  - node --version

script:
  - echo "--------- The images are Building -------------"
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed binlv2011/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user binlv2011/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend binlv2011/udagram-frontend:v1
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy binlv2011/udagram-reverseproxy:v1
  - echo "-------- All images successfully built -----------"

after_success:
  - echo "------- Logging in to Docker Hub --------"
  - echo "$DOCKER_PASSWORD" | docker login -u "binlv2011" --password-stdin
  - echo "-------------- Pushing images to Docker Hub -------"
  - docker push binlv2011/udagram-api-feed:v1
  - docker push binlv2011/udagram-api-user:v1
  - docker push binlv2011/udagram-frontend:v1
  - docker push binlv2011/udagram-reverseproxy:v1

notifications:
  email: false
